import json
import subprocess
from pathlib import Path

from taste_pinned_work_unit import (
    ACTIVE_PIN,
    DEFAULT_PROJECTION,
    DEFAULT_QUEUE,
    build_pinned_work_unit,
    read_jsonl,
    validate_pin_authority,
)

TASTE_SEMANTIC_WORK_CODE = 'resolve_grounded_negative_analysis'


def select_taste_semantic_rows(rows):
    """Preserve canonical queue order while excluding work owned by another semantic stage."""
    selected = []
    for row in rows:
        work = row.get('work_required')
        if isinstance(work, list) and TASTE_SEMANTIC_WORK_CODE in work:
            selected.append(row)
    return selected


def _head_bytes(repo_root, path):
    rel = Path(path).resolve().relative_to(Path(repo_root).resolve()).as_posix()
    proc = subprocess.run(
        ['git', 'show', f'HEAD:{rel}'],
        cwd=repo_root,
        capture_output=True,
        check=False,
    )
    return proc.stdout if proc.returncode == 0 else None


def normalize_next_pin(
    *,
    repo_root=Path('.'),
    pin_path=ACTIVE_PIN,
    queue_path=DEFAULT_QUEUE,
    projection_path=DEFAULT_PROJECTION,
):
    repo_root = Path(repo_root).resolve()
    pin_path = Path(pin_path).resolve()
    queue_path = Path(queue_path).resolve()
    projection_path = Path(projection_path).resolve()

    if not pin_path.exists():
        return {'status': 'no_active_pin'}

    raw = pin_path.read_bytes()
    pin = json.loads(raw.decode('utf-8'))
    validate_pin_authority(pin)

    if all(TASTE_SEMANTIC_WORK_CODE in row['work_required'] for row in pin['ordered_rows']):
        return {
            'status': 'active_pin_already_taste_semantic',
            'ordered_work_unit_sha256': pin['ordered_work_unit_sha256'],
            'count': len(pin['ordered_rows']),
        }

    # An already durable pin is immutable authority. This helper is allowed to
    # normalize only the next pin generated by process_taste_inbox.py in the
    # current uncommitted workflow transaction.
    if _head_bytes(repo_root, pin_path) == raw:
        raise ValueError('Refusing to rewrite a durable active Taste pin')

    rows = select_taste_semantic_rows(read_jsonl(queue_path))
    if not rows:
        pin_path.unlink()
        return {'status': 'removed_new_nonsemantic_pin_no_taste_work', 'count': 0}

    projection = json.loads(projection_path.read_text(encoding='utf-8'))
    next_pin = build_pinned_work_unit(
        projection,
        rows,
        pin['profile_identity'],
        authority='canonical_git_pre_semantic_work_unit_pin',
    )
    pin_path.write_text(json.dumps(next_pin, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    return {
        'status': 'normalized_new_next_taste_semantic_pin',
        'ordered_work_unit_sha256': next_pin['ordered_work_unit_sha256'],
        'count': len(next_pin['ordered_rows']),
    }


def main():
    result = normalize_next_pin()
    print(json.dumps(result, indent=2))


if __name__ == '__main__':
    main()
